language: c
sudo: required
install: 
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh  
script: 
  - bash -ex .travis-opam.sh
  - bash -ex ./coverage.sh
env:
  global:
   - PINS="distributed:. distributed-lwt:."
  matrix:
    - OCAML_VERSION=4.02 PACKAGE=distributed-lwt EXTRA_DEPS="bisect_ppx ocveralls"
    - OCAML_VERSION=4.03 PACKAGE=distributed-lwt EXTRA_DEPS="bisect_ppx ocveralls"
    - OCAML_VERSION=4.04 PACKAGE=distributed-lwt EXTRA_DEPS="bisect_ppx ocveralls"     
    - OCAML_VERSION=4.05 PACKAGE=distributed-lwt EXTRA_DEPS="bisect_ppx ocveralls"    
    - OCAML_VERSION=4.06 PACKAGE=distributed-lwt EXTRA_DEPS="bisect_ppx ocveralls"    
os:
  - linux
  - osx
