language: c
sudo: required
install: 
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh  
script: 
  - bash -ex .travis-opam.sh
env:
  global:
    - PINS="distributed"
  matrix:
    - OCAML_VERSION=4.02 PACKAGE=distributed_lwt
    - OCAML_VERSION=4.03 PACKAGE=distributed_lwt
    - OCAML_VERSION=4.04 PACKAGE=distributed_lwt      
    - OCAML_VERSION=4.05 PACKAGE=distributed_lwt      
    - OCAML_VERSION=4.06 PACKAGE=distributed_lwt      
os:
  - linux
  - osx
