platform:
  - x64

image: Visual Studio 2015

environment:
  CYG_ROOT: cygwin64
  CYG_ARCH: x86_64
  CYG_CACHE: C:/cygwin/var/cache/setup
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/  
  
  matrix:
    - OCAML_BRANCH: 4.05.0
    - OCAML_BRANCH: 4.06.0
  
install:
  - echo Installing necessary packages for opam install   
  - set CYGWIN="nodosfilewarning winsymlinks:native"
  - C:\cygwin64\setup-x86_64.exe --root=C:\cygwin64 --quiet-mode --no-desktop --no-startmenu --packages=perl,curl,diffutils,rsync,git,unzip,gzip,tar,make,mingw64-i686-gcc-core,mingw64-x86_64-gcc-core,m4,patch
  - C:\cygwin64\bin\bash.exe -lc "echo \"none /cygdrive cygdrive noacl,binary,posix=0,user 0 0\" > /etc/fstab"
  - echo Installing opam
  - cd C:\projects
  - appveyor DownloadFile "https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.1/opam64.tar.xz" -FileName "opam64.tar.xz" 
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/ && tar -xf 'opam64.tar.xz'"
  - C:\cygwin64\bin\bash.exe -lc "echo Username is `whoami`"
  - C:\cygwin64\bin\bash.exe -lc "/cygdrive/c/projects/opam64/install.sh  --prefix /usr/`whoami`"
  - C:\cygwin64\bin\bash.exe -lc "opam.exe init mingw 'https://github.com/fdopen/opam-repository-mingw.git' --comp \"$OCAML_BRANCH\"+mingw64c --switch \"$OCAML_BRANCH\"+mingw64c"
  - C:\cygwin64\bin\bash.exe -lc "eval $(opam.exe config env)"

build_script:
  - opam pin add distributed .
  - opam pin add distributed-lwt .
  - opam pin add lwt https://github.com/ocsigen/lwt.git\#safer-semantics   
  - opam install -v -t distributed-lwt
  
