platform:
  - x64

image: Visual Studio 2017

environment:
  CYG_ROOT: cygwin64
  CYG_ARCH: x86_64
  CYG_CACHE: C:/cygwin/var/cache/setup
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  
  matrix:
    - OCAML_BRANCH: 4.05
    - OCAML_BRANCH: 4.06
  
cache:
  - C:\projects\opam\bootstrap
  - C:\projects\opam\src_ext\archives

install:
  - set DISTPROJDIR=%APPVEYOR_BUILD_FOLDER%
  - echo Distributed project dir %DISTPROJDIR%
  - set APPVEYOR_BUILD_FOLDER=C:\projects\opam
  - cd C:\projects
  - echo APPVEYOR_BUILD_FOLDER dir %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/ocaml/opam.git opam
  - echo Installing necessary packages for opam build 
  - C:\cygwin64\setup-x86_64.exe --root=C:\cygwin64 --quiet-mode --no-desktop --no-startmenu --packages=make,mingw64-i686-gcc-core,mingw64-x86_64-gcc-core,m4,patch
  - echo Builing OCaml  
  - C:\cygwin64\bin\bash.exe -lc "make cold"
  - echo Builing opam 
  - C:\cygwin64\bin\bash.exe -lc "make cold-install"
  - opam switch %OCAML_BRANCH%
  - opam config env
  - opam install bisect_ppx 

build_script:
  - cd "%DISTPROJDIR%"
  - opam pin add distributed .
  - opam pin add distributed-lwt .
  - opam pin add lwt https://github.com/ocsigen/lwt.git\#safer-semantics   
  - opam install -v -t distributed-lwt
  
