platform:
  - x64

image: Visual Studio 2015

environment:
  CYG_ROOT: cygwin64
  CYG_ARCH: x86_64
  CYG_CACHE: C:/cygwin/var/cache/setup
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  
  matrix:
    - OCAML_PORT: 4.05
    - OCAML_PORT: 4.06
  
install:
  - set CYGWIN="nodosfilewarning winsymlinks:native"
  - set DISTPROJDIR=%APPVEYOR_BUILD_FOLDER%
  - echo Distributed project dir %DISTPROJDIR%
  - cd C:\projects
  - git clone https://github.com/ocaml/opam.git opam
  - echo Installing necessary packages for opam build 
  - C:\cygwin64\setup-x86_64.exe --root=C:\cygwin64 --quiet-mode --no-desktop --no-startmenu --packages=gzip,tar,make,mingw64-i686-gcc-core,mingw64-x86_64-gcc-core,m4,patch
  - C:\cygwin64\bin\bash.exe -lc "echo \"none /cygdrive cygdrive noacl,binary,posix=0,user 0 0\" > /etc/fstab"
  - echo Installing glpk
  - appveyor DownloadFile "http://ftp.gnu.org/gnu/glpk/glpk-4.35.tar.gz" -FileName "glpk.tar.gz"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/ && gzip -d glpk.tar.gz"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/ && tar -x < glpk.tar"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/glpk* && ./configure"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/glpk* && make"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/glpk* && make install"
  - echo Installing mccs
  - appveyor DownloadFile "http://www.i3s.unice.fr/~cpjm/misc/mccs-1.1-srcs.tgz" -FileName "mccs"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/ && gzip -d mccs.tar.gz"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/ && tar -x < mccs.tar"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/mccs* && make USEGLPK=1"
  - echo Building OCaml
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && make compiler OCAML_PORT=mingw64"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && ./configure --without-mccs"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && make lib-ext"
  - echo Building opam 
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && make"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && make install"

build_script:
  - cd "%DISTPROJDIR%"
  - opam init
  - opam switch %OCAML_PORT%
  - opam config env
  - opam pin add distributed .
  - opam pin add distributed-lwt .
  - opam pin add lwt https://github.com/ocsigen/lwt.git\#safer-semantics   
  - opam install -v -t distributed-lwt
  
