#platform:
  - x64

image: Visual Studio 2017

environment:
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: cygwin64
  CYG_ARCH: x86_64
  OCAML_PORT:
  CYG_CACHE: C:/cygwin/var/cache/setup
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  DEP_MODE: lib-ext

  matrix:
    - OCAML_BRANCH: 4.05
    - OCAML_BRANCH: 4.06
  
cache:
  - C:\projects\opam\bootstrap
  - C:\projects\opam\src_ext\archives

install:
  - set DISTPROJDIR=%APPVEYOR_BUILD_FOLDER%
  - echo Distributed project dir %DISTPROJDIR%
  - set APPVEYOR_BUILD_FOLDER=C:\projects\opam
  - cd C:\projects
  - echo APPVEYOR_BUILD_FOLDER dir %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/ocaml/opam.git opam
  - echo Builing opam "%APPVEYOR_BUILD_FOLDER%\appveyor_build.cmd"
  - call "%APPVEYOR_BUILD_FOLDER%\appveyor_build.cmd" install  
  - echo Installing opam "%APPVEYOR_BUILD_FOLDER%\appveyor_build.cmd"
  - call "%APPVEYOR_BUILD_FOLDER%\appveyor_build.cmd" build
  - opam switch %OCAML_BRANCH%
  - opam config env
  - opam install bisect_ppx 

build_script:
  - cd "%DISTPROJDIR%"
  - opam pin add distributed .
  - opam pin add distributed-lwt .
  - opam pin add lwt https://github.com/ocsigen/lwt.git\#safer-semantics   
  - opam install -v -t distributed-lwt
  
