# AppVeyor config using https://github.com/Chris00/ocaml-appveyor
# build using jbuilder => ocaml >= 4.05

environment:
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64

  matrix:
    - OPAM_SWITCH: 4.05
    - OPAM_SWITCH: 4.06

install:
  - appveyor DownloadFile "https://raw.githubusercontent.com/Chris00/ocaml-appveyor/master/install_ocaml.cmd" -FileName "C:\install_ocaml.cmd"
  - C:\install_ocaml.cmd
  - git clone https://github.com/ocaml/opam.git opam_dir
  - cd opam_dir
  - call "appveyor_build.cmd" build
  - call "appveyor_build.cmd" install
  - opam install bisect_ppx 

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - opam pin add distributed .
  - opam pin add distributed-lwt .
  - opam pin add lwt https://github.com/ocsigen/lwt.git\#safer-semantics   
  - opam install -v -t distributed-lwt
  
