platform:
  - x64

image: Visual Studio 2015

environment:
  CYG_ROOT: cygwin64
  CYG_ARCH: x86_64
  CYG_CACHE: C:/cygwin/var/cache/setup
  CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/  
  
  matrix:
    - OCAML_BRANCH: 4.05
    - OCAML_BRANCH: 4.06
  
install:
  - set DISTPROJDIR=%APPVEYOR_BUILD_FOLDER%
  - echo Distributed project dir %DISTPROJDIR%
  - set CYGWIN="nodosfilewarning winsymlinks:native"
  - echo Installing necessary packages for opam install 
  - C:\cygwin64\setup-x86_64.exe --root=C:\cygwin64 --quiet-mode --no-desktop --no-startmenu --packages=gzip,tar,make,mingw64-i686-gcc-core,mingw64-x86_64-gcc-core,m4,patch
  - C:\cygwin64\bin\bash.exe -lc "echo \"none /cygdrive cygdrive noacl,binary,posix=0,user 0 0\" > /etc/fstab"
  - appveyor DownloadFile "https://raw.githubusercontent.com/Chris00/ocaml-appveyor/master/install_ocaml.cmd" -FileName "C:\install_ocaml.cmd"
  - C:\install_ocaml.cmd
  - echo Installing opam 
  - cd C:\projects
  - git clone https://github.com/ocaml/opam.git opam
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && ./configure"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && make lib-pkg"  
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && make"
  - C:\cygwin64\bin\bash.exe -lc "cd /cygdrive/c/projects/opam && make install"

build_script:
  - cd "%DISTPROJDIR%"
  - opam init
  - opam switch %OCAML_BRANCH%
  - opam config env
  - opam pin add distributed .
  - opam pin add distributed-lwt .
  - opam pin add lwt https://github.com/ocsigen/lwt.git\#safer-semantics   
  - opam install -v -t distributed-lwt
  
