# AppVeyor config using https://github.com/Chris00/ocaml-appveyor
# build using jbuilder => ocaml >= 4.05

environment:
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64

  matrix:
    - OPAM_SWITCH: 4.05
    - OPAM_SWITCH: 4.06

install:
  - appveyor DownloadFile "https://raw.githubusercontent.com/Chris00/ocaml-appveyor/master/install_ocaml.cmd" -FileName "C:\install_ocaml.cmd"
  - C:\install_ocaml.cmd

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - jbuilder subst
  - jbuilder build -p distributed-lwt
  - jbuilder runtest -p distributed-lwt
  
